name: OreGenerator
main: io.github.pirgosth.oregenerator.OreGenerator
version: 1.0
api-version: 1.18
softdepend: [Multiverse-Core]
author: Pirgosth
commands:
  og:
    description: OreGenerator config command
    usage: /<command> [disabled | enable | list | reload]
permissions:
  oregenerator.commands.disable:
    description: Allows disable command
    default: op
  oregenerator.commands.enable:
    description: Allows enable command
    default: op
  oregenerator.commands.list:
    description: Allows list command
    default: op
  oregenerator.commands.reload:
    description: Allows reload command
    default: op
  oregenerator.*:
    description: Wildcard permission
    default: op
    children:
      oregenerator.commands.enable: true
      oregenerator.commands.disable: true
      oregenerator.commands.list: true
      oregenerator.commands.reload: true
